/**
 * @author Zahir Hadi Athallah <contactzsoft@gmail.com>
 * @license MIT
 * @app SekolahYuk
 */

export const STUDENT_DETAIL_REQUEST = 'STUDENT_DETAIL_REQUEST';
export const STUDENT_DETAIL_SUCCESS = 'STUDENT_DETAIL_SUCCESS';
export const STUDENT_DETAIL_FAIL = 'STUDENT_DETAIL_FAIL';

export const GET_ALL_REGISTERED_REQUEST = 'GET_ALL_REGISTERED_REQUEST';
export const GET_ALL_REGISTERED_SUCCESS = 'GET_ALL_REGISTERED_SUCCESS';
export const GET_ALL_REGISTERED_FAIL = 'GET_ALL_REGISTERED_FAIL';

export const STUDENT_TEST_LIST_REQUEST = 'STUDENT_TEST_LIST_REQUEST';
export const STUDENT_TEST_LIST_FAIL = 'STUDENT_TEST_LIST_FAIL';
export const STUDENT_TEST_LIST_SUCCESS = 'STUDENT_TEST_LIST_SUCCESS';
export const STUDENT_TEST_LIST_RESET = 'STUDENT_TEST_LIST_RESET';
