/**
 * @author Zahir Hadi Athallah <contactzsoft@gmail.com>
 * @license MIT
 * @app SekolahYuk
 */


export const TEACHER_LIST_REQUEST = 'TEACHER_LIST_REQUEST';
export const TEACHER_LIST_SUCCESS = 'TEACHER_LIST_SUCCESS';
export const TEACHER_LIST_FAIL = 'TEACHER_LIST_FAIL';

export const TEACHER_REQ_LIST_REQUEST = 'TEACHER_REQ_LIST_REQUEST';
export const TEACHER_REQ_LIST_SUCCESS = 'TEACHER_REQ_LIST_SUCCESS';
export const TEACHER_REQ_LIST_FAIL = 'TEACHER_REQ_LIST_FAIL';

export const TEACHER_UPDATEPERM_REQUEST = 'TEACHER_UPDATEPERM_REQUEST';
export const TEACHER_UPDATEPERM_SUCCESS = 'TEACHER_UPDATEPERM_SUCCESS';
export const TEACHER_UPDATEPERM_FAIL = 'TEACHER_UPDATEPERM_FAIL';
